# Generated by Django 5.0.4 on 2024-06-02 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('yslugi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('ysluga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yslugi.yslugi', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Записи',
                'verbose_name_plural': 'Записи',
                'db_table': 'cart',
            },
        ),
    ]
