# Generated by Django 5.0.6 on 2024-06-05 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cart_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Курсы пользователя', 'verbose_name_plural': 'Курсы пользователей'},
        ),
    ]
