# Generated by Django 5.0.6 on 2024-06-05 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yslugi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yslugi',
            options={'ordering': ('id',), 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
    ]
