# Generated by Django 5.0.4 on 2024-06-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yslugi', '0002_alter_yslugi_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='yslugi',
            name='urlyoutube',
            field=models.CharField(blank=True, max_length=500, unique=True, verbose_name='Ссылка на видео'),
        ),
    ]
