# Generated by Django 5.0.4 on 2024-06-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yslugi', '0003_yslugi_urlyoutube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yslugi',
            name='urlyoutube',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='Ссылка на видео'),
        ),
    ]
